server:
  port: 8083

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo:mongopassword@localhost:27017/booking_db?authSource=admin}



    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: booking-group
      auto-offset-reset: earliest

services:
  pricing-service:
    url: ${PRICING_SERVICE_URL:http://localhost:8084}
  location-service:
    url: ${LOCATION_SERVICE_URL:http://localhost:8082}
